name: election_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.8
  email_validator: ^2.0.1
  cached_network_image: ^3.2.0
  permission_handler: ^8.3.0
  google_fonts: ^2.2.0
  auto_size_text: ^3.0.0
  http: ^0.13.5
  intl: ^0.17.0
  syncfusion_flutter_gauges: ^20.3.47
  flutter_datetime_picker: ^1.5.1
  flutter_switch: ^0.3.2
  qr_code_scanner: ^1.0.1
  flutter_launcher_icons: ^0.10.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/img/logo.png
    - assets/img/user_sample.png
